opprop/checker-framework-inference

- src/checkers/inference/BaseInferrableChecker.java
- src/checkers/inference/InferenceMain.java
- src/checkers/inference/InferrableChecker.java
- src/checkers/inference/util/JaifBuilder.java
1.  using ASTPath instead of string comparisionto determine the kind of a annotation location. 
2.  change isInsertMethodBody() to isInsertMainModOfLocalVar(). 
3.  let checker decide whether to insert annotaions in main modifier of local variable.
> refactor jaifBuilder

- .classpath
- .gitignore
- .travis-build.sh
- README.md
- build.gradle
- src/checkers/inference/InferenceLauncher.java
- src/checkers/inference/InferenceMain.java
- src/checkers/inference/InferenceOptions.java
- src/checkers/inference/util/JaifSplitter.java
- tests.xml
* Add Sat4J test jar to classpath.
* Remove tests/deps directory and the extra copy step.
Everything is put into dist directory.
* Remove unused method.
* Replace arrays with Lists, use Class literals instead of Strings, and
other simplifications of the code.
* Make Readme markdown and add travis status.
* Improve markdown.
* Remove invocation of copytest target.
> A set of improvements to tests and launcher (#8)

- src/checkers/inference/DefaultSlotManager.java
- src/checkers/inference/ImpliedTypeAnnotator.java
- src/checkers/inference/InferenceAnnotatedTypeFactory.java
- src/checkers/inference/InferenceQualifierHierarchy.java
- src/checkers/inference/InferenceTypeVariableSubstitutor.java
- src/checkers/inference/InferenceVisitor.java
- src/checkers/inference/SlotManager.java
- src/checkers/inference/VariableAnnotator.java
- src/checkers/inference/dataflow/InferenceTransfer.java
- src/checkers/inference/dataflow/InferenceValue.java
- src/checkers/inference/model/serialization/CnfSerializerSolver.java
- src/checkers/inference/model/serialization/JsonDeserializer.java
- src/checkers/inference/solver/MaxSat2TypeSolver.java
- src/checkers/inference/util/ConstantToVariableAnnotator.java
- src/sparta/checkers/sat/PermissionSolver.java
- tests/checkers/inference/model/serialization/TestSerialization.java
Pull request #13 with the merging conflict fixation.
> Slotmanager

- build.gradle
this PR is a complement for #35 . Add some comments and remove un-used line as the code review comments in #35 .
> [complement PR] further documentation on gradle changes 

- .travis.yml
Try to solve the `unfinished travis error` by running travis test by docker.
> Use docker to run travis test.

- scripts/inference-dev
- src/checkers/inference/InferenceDevelLauncher.java
- src/checkers/inference/InferenceLauncher.java
- src/checkers/inference/VariableAnnotator.java
PR for pulling updates from typetools upstream.
> Update upstream 2017 09 05

- src/checkers/inference/util/CopyUtil.java
In `VariableAnnotator#annotateElementFromStore(elt, destAtm)`, if `VariableAnnotator#elementToAtm` has already cached an ATM for the given element, it will try to   
copy the annotations on that ATM to the given `destAtm`.
The original `CopyUtil` doesn't handle the case of copying from an Union type to another Union type. 
In this PR I add the code to handle this.
For a longer term goal, I remembered we discussed before, we should understand why we need this `CopyUtil` class, and see if we could remove this class.
As of the test case, unfortunately, the one I have is a file more than 100 LoC, and strangely if I removed some definitely unrelated code from that file, the crash caused by CopyUtil won't be trigged...
(It seems somehow the caching changed once the file becomes shorter... but I …
> CopyUtil: handle the case of copy from Union to Union.

- src/checkers/inference/solver/backend/SolverType.java
Add missing Z3 configuration in SolverType.
> Add Z3 configuration in SolverType.

- testing/dataflow/TestByteCodeMethodArrayComponentType.java
- testing/dataflow/TestCharInvalid.java
- testing/dataflow/TestCollectionTypeInvalid.java
- testing/dataflow/TestDoubleInvalid.java
- testing/dataflow/TestIntInvalid.java
- testing/dataflow/TestNewInvalid.java
- testing/dataflow/TestStringInvalid.java
- testing/dataflow/TestUpperBound1Invalid.java
- testing/dataflow/TestUpperBound2Invalid.java
- testing/dataflow/TestUpperBound3Invalid.java
- testing/dataflow/TestUpperBound4Invalid.java
Trying to solve Travis failure on upstream update PR for CF: https://github.com/opprop/checker-framework/pull/53
> Fix error format in dataflow test cases.

- src/checkers/inference/solver/backend/z3/Z3BitVectorFormatTranslator.java
- src/checkers/inference/solver/backend/z3/Z3Solver.java
- src/checkers/inference/solver/backend/z3/encoder/Z3BitVectorAbstractConstraintEncoder.java
- src/checkers/inference/solver/backend/z3/encoder/Z3BitVectorEqualityConstraintEncoder.java
- src/checkers/inference/solver/backend/z3/encoder/Z3BitVectorSubtypeConstraintEncoder.java
- Simplify Z3 Encoder logic.
- Add real empty value and contradictory value for Z3 encoders.
> Refactor Z3 Encoders

- build.gradle
- src/checkers/inference/DefaultSlotManager.java
- src/checkers/inference/InferenceMain.java
- src/checkers/inference/InferenceVisitor.java
- src/dataflow/DataflowAnnotatedTypeFactory.java
- src/dataflow/DataflowChecker.java
- src/dataflow/DataflowInferenceTreeAnnotator.java
- src/dataflow/solvers/classic/DataflowSolver.java
- src/dataflow/util/DataflowUtils.java
Note: Since typetools/CFI has a re-formatting change, which cause too many merge conflicts, I only cherry-pick the commit that synchronize CFI with CF changes.
I'm aware of this might cause future pulling updates from typetools becomes harder, but I believe anyway we need to resolve this huge divergence in the near future.
> Opprop upstream update 2017 11 14

- src/checkers/inference/InferenceAnnotatedTypeFactory.java
Use constructor from the super class that is called by the annonymous class new statement.
> Fix no VarAnnot on paramaters of annonymous class constructor

- scripts/inference-dev
> Correct java stub parser path in inference-dev script.

- .classpath
- .travis-build-without-test.sh
- build.gradle
- checker-framework-inference.iml
- scripts/buildZ3
- scripts/debugSplitJaif
- scripts/inference
- scripts/inference-dev
- scripts/launchDebugger
- scripts/splitJaif
- scripts/updateJaif
Note: Plume-core is packaged inside AFU.jar
> Fix plume.jar path references in build scripts, and z3 build script if statement.

- src/checkers/inference/CheckerFrameworkUtil.java
- src/checkers/inference/InferenceMain.java
Instead of simply returning success or not, return raw compiler result and let result handler to decide what action to take
> Result handler refactor

- .travis.yml
- src/hardcoded/qual/MaybeHardcoded.java
- src/hardcoded/qual/NotHardcoded.java
- src/interning/InterningAnnotatedTypeFactory.java
- src/nninf/NninfAnnotatedTypeFactory.java
- src/nninf/qual/NonNull.java
This PR is cycling depends on https://github.com/opprop/checker-framework/pull/64 .
I will directly merge this one, and then try to see if the other one passed.
> Update upstream 2018 Feb 12

- src/checkers/inference/model/serialization/ToStringSerializer.java
- src/checkers/inference/solver/DebugSolver.java
In `DebugSolver`:
- generate sublist upon first encounter of a type of slot in `.partitionSlots()`
- add newline between printing of different slot types
In `ToStringSerializer`:
- sorts varslots (and its subclasses) based on slot ID, and any other kind of slots based on serialized string content
- changed indentation to 2 spaces
- indent printout of slots to be consistent with printout of constraints
- update `serialize(ConstantSlot slot)` to use `AnnotationFormatter`
- update `serialize(XXXConstraints )` to use string builders
- ensure indentation levels never go below zero
- remove extra newlines in ast path printouts (there used to be new lines after every astpath, but no new lines separating slots of the other slot types such as CombVarSlot, so this makes it more consistent)
- …
> Update DebugSolver and ToStringSerializer slot support and printout format

- src/checkers/inference/InferenceVisitor.java
Reverts opprop/checker-framework-inference#166
improper merge
> Revert "Upstream update mar 05"

- .travis-build.sh
- src/checkers/inference/model/Constraint.java
- src/checkers/inference/model/ConstraintManager.java
- src/checkers/inference/model/ImplicationConstraint.java
- src/checkers/inference/model/Serializer.java
- src/checkers/inference/model/serialization/CnfVecIntSerializer.java
- src/checkers/inference/model/serialization/JsonSerializer.java
- src/checkers/inference/model/serialization/ToStringSerializer.java
- src/checkers/inference/solver/backend/AbstractFormatTranslator.java
- src/checkers/inference/solver/backend/encoder/AbstractConstraintEncoderFactory.java
- src/checkers/inference/solver/backend/encoder/ConstraintEncoderCoordinator.java
- src/checkers/inference/solver/backend/encoder/ConstraintEncoderFactory.java
- src/checkers/inference/solver/backend/encoder/implication/ImplicationConstraintEncoder.java
- src/checkers/inference/solver/backend/logiql/LogiQLFormatTranslator.java
- src/checkers/inference/solver/backend/logiql/encoder/LogiQLConstraintEncoderFactory.java
- src/checkers/inference/solver/backend/maxsat/MaxSatFormatTranslator.java
- src/checkers/inference/solver/backend/maxsat/encoder/MaxSATConstraintEncoderFactory.java
- src/checkers/inference/solver/backend/maxsat/encoder/MaxSATImplicationConstraintEncoder.java
- src/checkers/inference/solver/backend/z3/encoder/Z3BitVectorConstraintEncoderFactory.java
- src/checkers/inference/solver/util/PrintUtils.java
1. Add ImplicationConstraint: a ^ b ^ c -> d(single `Constraint`), in which a,b,c,d are `Constraint`. LHS is  conjunction of arbituary `Constraint`s; RHS is a single any `Constraint`.
2. Update `Encoder`, `EncoderFactory`,`FormatTranslator` accordingly.
3. Provide implementation of `MaxSATImplicationConstraintEncoder`.
4. Improve string representation of `RefinementVariableSlot`.
> Add ImplicationConstraint

- .travis-build.sh
- .travis.yml
Actually do the downstream tests.
For now, we skip unit-inference and ontology.
> Enable Downstream tests.

- gradle/wrapper/gradle-wrapper.properties
- src/checkers/inference/InferenceLauncher.java
- src/checkers/inference/InferenceMain.java
- src/checkers/inference/InferenceOptions.java
- src/checkers/inference/InferenceQualifierHierarchy.java
- src/checkers/inference/dataflow/InferenceAnalysis.java
- src/checkers/inference/model/ExistentialConstraint.java
- src/checkers/inference/model/serialization/ToStringSerializer.java
- src/checkers/inference/util/JaifBuilder.java
- src/checkers/inference/util/JaifFileReader.java
- tests/checkers/inference/test/CFInferenceTest.java
- tests/checkers/inference/test/InferenceResult.java
- tests/checkers/inference/test/InferenceTestConfigurationBuilder.java
- tests/checkers/inference/test/InferenceTestExecutor.java
- tests/checkers/inference/test/InsertionResult.java
Merge with https://github.com/opprop/checker-framework/pull/128.
> Update from typetools 2020-05-04.

- tests/checkers/inference/test/CFInferenceTest.java
Corresponding PR: https://github.com/opprop/checker-framework/pull/136
> Update from typetools 2020-06-03

- scripts/inference
- scripts/inference-dev
Merge with https://github.com/opprop/checker-framework/pull/139.
> Update from typetools 2020-06-09

- README.md
`GeneralSlover` has been renamed with `SolverEngine`.
> Update solver name in README.md

- src/checkers/inference/InferenceQualifierHierarchy.java
- src/checkers/inference/InferenceVisitor.java
- src/checkers/inference/solver/constraintgraph/GraphBuilder.java
- src/checkers/inference/solver/strategy/GraphSolvingStrategy.java
- src/dataflow/solvers/classic/DataflowSolver.java
- src/dataflow/solvers/general/DataflowGraphSolvingStrategy.java
fixes #218
This PR works with downstream PR https://github.com/opprop/security-demo/pull/7 because security-demo is special in having non-top default.
> Validate constructor results. Fixes issue #218.

- src/checkers/inference/ConstraintNormalizer.java
- src/checkers/inference/ExistentialVariableInserter.java
- src/checkers/inference/InferenceQualifierHierarchy.java
- src/checkers/inference/InferenceVisitor.java
- src/checkers/inference/VariableAnnotator.java
- src/checkers/inference/dataflow/InferenceValue.java
- src/checkers/inference/util/CopyUtil.java
- src/checkers/inference/util/JaifBuilder.java
- src/checkers/inference/util/JaifFileReader.java
- src/dataflow/DataflowAnnotatedTypeFactory.java
- src/dataflow/solvers/classic/DatatypeSolver.java
Idea has code inspection which can help with finding potential issues
This PR addresses some of the items under section "Probable bugs".
> Address some issues from IDEA code inspection

- scripts/buildDLJC
This is helpful for feature updates on "opprop/do-like-javac"
> Always clone related do-like-javac

- .ci-build-without-test.sh
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- src/checkers/inference/InferenceAnnotatedTypeFactory.java
- src/checkers/inference/VariableAnnotator.java
- src/checkers/inference/util/CopyUtil.java
- src/checkers/inference/util/InferenceUtil.java
Adding dependency to AFU and changing `clearPrimaryAnnotations()` to `clearAnnotations`
> Eisop 3.18 update

- testdata/ostrusted-inferrable-test/AnonymousProblem.java
Fixed by https://github.com/opprop/checker-framework/pull/199
Additional tests should be added.
> Fix false-positive type checking error

- scripts/inference-dev
- src/checkers/inference/InferenceAnnotatedTypeFactory.java
- src/checkers/inference/model/ConstraintManager.java
- src/interning/InterningVisitor.java
- src/nninf/NninfAnnotatedTypeFactory.java
Many changes have been introduced by the latest eisop (https://github.com/opprop/checker-framework/pull/206), and this PR is to make the Inference work properly on top of the changes.
> Changes for updates from eisop

- build.gradle
- src/checkers/inference/ExistentialVariableInserter.java
- src/checkers/inference/util/InferenceUtil.java
I have tested this pr both in master and in update-3.21.4-eisop1 branch of CF.
> Keep ub/lb when calling removeAnnotation

- README.md
Update CI badge in README.md to link to GitHub Actions
> Update CI link

- README.md
Replaces the link to EISOP and also fixes some typos.
> Update links to the manual and fix typos

- scripts/inference-dev
- src/checkers/inference/DefaultSlotManager.java
- src/checkers/inference/InferenceAnnotatedTypeFactory.java
- src/checkers/inference/InferenceQualifierHierarchy.java
- src/checkers/inference/VariableAnnotator.java
- src/checkers/inference/dataflow/InferenceAnalysis.java
- src/checkers/inference/dataflow/InferenceValue.java
- src/checkers/inference/solver/backend/maxsat/MaxSatFormatTranslator.java
- src/checkers/inference/solver/frontend/LatticeBuilder.java
- src/checkers/inference/util/ASTPathUtil.java
- src/checkers/inference/util/InferenceUtil.java
- src/dataflow/solvers/general/DataflowGraphSolvingStrategy.java
- src/sparta/checkers/SimpleFlowAnnotatedTypeFactory.java
Relevant PRs are:
For CF: https://github.com/opprop/checker-framework/pull/246
For Annotation-tools: https://github.com/opprop/annotation-tools/pull/129
For JDK: https://github.com/opprop/jdk/pull/4
For Stubparser: https://github.com/opprop/stubparser/pull/55
> Update to EISOP 3.32-eisop1 from 3.28-eisop1
