src/checkers/inference/InferenceOptions.java
When `javac` compiles a java file, the default classpath of this target file is current working directory `./`
To make `CF Inference` consist with `javac`, I add a default value of `InferenceOptions#targetclasspath` as `.`
This could let a user save the explicit declaration of the classpath of a target program when the classpath is just the default current working directory.
=> add default target classpath in inferenceOptions

src/checkers/inference/InferenceAnnotatedTypeFactory.java, src/sparta/checkers/SimpleFlowAnnotatedTypeFactory.java
1. removed deprecate method call `InferenceMain#getRealTypeFactory()`
2. let `createSupportedTypeQualifiers()` return fresh set.
3. This PR depends on [opprop/checker-framework #1](https://github.com/opprop/checker-framework/pull/1)
=> remove deprecate method call in InferenceATF

src/checkers/inference/InferenceAnnotatedTypeFactory.java
`postInit()` method in `AnnotatedTypeFactory` should be called by the real runtime class during initialisation.
Otherwise, it may cause using uninitialised fields in a subclass during executing `postInit()`, which would cause some tricky exceptions. 
Currently, it seems we should follow the pattern in `BaseTypeATF`:
https://github.com/typetools/checker-framework/blob/master/framework/src/org/checkerframework/common/basetype/BaseAnnotatedTypeFactory.java#L25
Is there any better design to avoid forcing each subclass call the `postInit()`? @wmdietl @Jianchu @topnessman
=> only call postInit when implicit this is InferenceATF itself.

src/checkers/inference/InferenceLauncher.java, src/checkers/inference/InferenceMain.java, src/checkers/inference/InferenceOptions.java
add cfArgs option in `InferenceOption`. 
User could use follow a space-seperated format to pass cfArgs when launching CF Inference:
```bash
--cfArgs="-Axxx=xxx -Ayyy"
```
=> add cfArgs in InferenceOptions. also parsing method in InferenceMain

src/checkers/inference/VariableAnnotator.java
Originally `VariableAnnotator#createEquivalentSlotConstraints` will not create constant slot for a polymorphic qualifier.
However, this would cause `PolyReplacer` never replace a polymorphic qualifier by VarAnnot, in which would cause polymorphic qualifier doesn't work.
https://github.com/opprop/checker-framework-inference/blob/master/src/checkers/inference/InferenceQualifierPolymorphism.java#L76
=> remove wrong if-condition to enable polymorphism

src/checkers/inference/DefaultSlotManager.java, src/checkers/inference/SlotManager.java, src/checkers/inference/model/serialization/CnfVecIntSerializer.java, src/checkers/inference/solver/MaxSat2TypeSolver.java
`SlotManager#nextId()` is better to be a private method as the discussion here:
- pascaliUWat/checker-framework-inference#3
- https://github.com/opprop/generic-type-inference-solver/pull/6
This PR makes `nextId()` private and clean up the `nextId()` usage in checker-framework-inference
=> Make SlotManager#nextId private

.travis.yml, src/checkers/inference/InferenceAnnotatedTypeFactory.java, src/checkers/inference/InferenceMain.java, src/checkers/inference/model/ConstraintManager.java, src/sparta/checkers/SimpleFlowAnnotatedTypeFactory.java
In `ConstraintManager`, it use `qualifierHierarchy` to make some type checking (e.g. validating type relationship before adding a subtypeConstraint) and optimizations(e.g. creating EqualityConstraint instead of SubtypeConstraint when sub is top or super is bot). However, it used the `InferenceQualifierHierarchy` to check qualifier orders, which is wrong because `InferenceQualifierHierarchy` isn't for maintaining the real qualifier hierarchy.
In this PR, I changed the reference to `qualifierHierarchy` in `ConstraintManager` to be the realQualifierHierarchy. In order to achieve this, following changes has been made:
- Passed `RealTypeFactory` reference when initializing `constraintManager` in `InferenceMain`.
- Changed `qualifierHierarchy` refer to the real qualifier hierarchy in …
=> Fixed wrong usage of qualifierHierarchy in ConstraintManager.

src/checkers/inference/DefaultSlotManager.java
In `DefaultSlotManager`, it caches slots that created before to avoid duplication. These slots are identified by their `AnnotationLocation`. This identity is effective except in the case of `MissingLocation`. That means, if we cache slots for `MissingLocation`, we will get a slot that mapped to all `MissingLocation`, in some cases this will cause constraints generated has problem (As they using the same slot for different `MissingLocation` to construct constraints).
This PR is a quick fix for this problem -- In `createVariableSlot` and `createRefinementSlot` method, directly create a new slot for `MissingLocation` instead of caching them.
A minimum test case testing against on `Ontology`type system show as below: (contains two files and calling a byte code method):
```java
\\First File …
```
=> [DefaultSlotManager] Avoid caching for missing location slot.

src/checkers/inference/InferenceAnnotatedTypeFactory.java
To be honest, I don't fully understand the fix.
CFI currently will crash on below language construct:
```java
import java.util.Collections;
import java.util.List;
class EmptyEqualCons<T> {
protected List<T> genericList;
public List<T> getUnModifiableGenericList() {
return Collections.unmodifiableList(this.genericList);
}
}
```
And the stack trace is:
<pre>
INFO: error: Create equality constraint with null argument. Subtype: null Supertype: @ontology.qual.Ontology(values={ontology.qual.OntologyValue.BOTTOM})
Compilation unit: debug/EmptyEqualCons.java
Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25) …
=> Passing realATF when finding typeArgs by AnnotationTypes

src/checkers/inference/VariableAnnotator.java, testdata/ostrusted/AnonymousProblem.java
For anonymous type, maybe we should always try to find the proper super type ATM representing this anonymous type, instead of only find it when the type is an IDENTIFIER.
E.g. given below code, the kind of anonymous type is MEMBER_SELECT, but we still want to find a proper supertype ATM represents it.
```java
OutterI.InnerI<Object> f = new OutterI.InnerI<Object>() {
};
```
So overall, I don't see is there any harm if we always find a proper super type ATM represents an anonymous type. Am I missing some corner cases? @wmdietl @topnessman 
Thanks!
=> Always found proper ATM for an anonymous type.

src/checkers/inference/VariableAnnotator.java, testdata/ostrusted/MemberSelectEnclosingNull.java
As discussed with Prof. Dietl @wmdietl  last week, should only visit enclosing type of a memberSelect tree if the enclosing type is non-null. This is because for some memberSelect tree, it's enclosing type is null, e.g. for bellow code:
```java
class C {
public java.util.Timer t = new java.util.Timer();
}
```
`public java.util.Timer` is also a memberSelect tree, and it's enclosing type is null.
I've add the test case into OsTrusted Type system, as this is one of the base Type system in CFI.
=> VariableAnnotator#visitDeclared#case MEMBER_SELECT: Only visit enclosing type if it is non-null.

src/checkers/inference/InferenceVisitor.java, testdata/ostrusted/PrimitiveTypeAssignment.java
In `InferenceVisitor#commonAssignmentCheck()` it will check the subtype relationship between LHS and RHS. In the case of RHS is primitive type, it will first get the boxed type of RHS, then check if the boxed type are the subtype of LHS.
This boxing is improper. E.g. for below example:
```java
Byte b = 1;
```
The boxed type of RHS would be `Integer`, which would failed the isSubtype check.
Very strange, in this case I would expect the original code will just failed the subtype check. However, actually when it internally delegate this subtype check to `DefaultTypeHierarchy` with checking two incomparable types, it will cause an ErrorAbort exception thrown from CF. The reason of why CF throw an exception instead of returning  false need to be further investigate and understanding the logic. …
=> Don't get Boxed type before delegate to aTypeFactory to judge subtype relationship

src/checkers/inference/InferenceQualifierHierarchy.java
In `InferenceQualifierHierarchy#leastUpperBound(a1, a2)`, it delegates the LUB computation to super class when both `a1` and `a2` are nonVarAnnots.
Current implementation is mal-logiced, as in the super class it will actually using `isSubtype()` to judge the subtype relationship between `a1` and `a2`, and `isSubtype()` has been override in `InferenceQualHierarchy` to always return true if both annos passed in are nonVarAnnos. Therefore, current implementation in `inferenceQualHierarchy` actually will always return `a2` as the LUB, when `a1` and `a2` are both nonVarAnnos (due to the super class implementation first judge if `a1` is subtype of `a2`, which always returned true by `inferenceQualHierarchy`).
I think a more reasonable implementation would be delegating the computation to …
=> Use realQual to compute LUB when both annos are not varAnnot.

src/checkers/inference/VariableAnnotator.java
In `VariableAnnotator`, it try to create a primary VarAnnotation for each visited ATM.
During this process, it delegate the responsibility of making the `varAnnotation` consistent with pre-annotated real annotations or implicit by a method called `createEquivalentSlotConstraints()`.
In this PR I cleaned up this method.
Overview change:
- renaming: from `createEquivalentSlotConstraints()` to `replaceOrCreateEquivalentVarAnno()`. 
- The original naming is confusing. It doesn't create any constraints, instead, it just try to create/replace the real annotations(if any) by the equivalent VarAnnos on the given ATM.
- Fixing the logic: Original logic doesn't consider the case of existing Annotations on the ATM could only have existed VarAnnos without any real Annotations. In this case, the …
=> Clean up createEquivalentSlotConstraints method in VariableAnnotator.

scripts/inference
Export `DYLD_LIBRARY_PATH` environment variable in inference script, so that we can also use Z3 backend when using inference script instead of inference-dev script.
=> Add missing Z3 dylib environment variable in inference script.

src/checkers/inference/InferenceAnnotatedTypeFactory.java, src/checkers/inference/VariableAnnotator.java
VariableAnnotator indirectly creates LUB constraints via invoking the inference qualifier hierarchy to create a result VarAnnot for each binary tree visit. Units Inference must be able to override this behavior in order to replace LUB constraints with arithmetic constraints.
This PR allows VariableAnnotator to be subclassable by introducing createVariableAnnotator() in InferenceATF, and lifting some of the fields in VariableAnnotator from private to protected for subclass use.
=> Make VariableAnnotator subclassable

src/checkers/inference/util/JaifBuilder.java
Annotation fields of String type were printed out as "java.lang.String" instead of the expected "String" keyword in jaif files by JaifBuilder. This PR fixes the problem.
=> Fix JaifBuilder not outputting String annotation fields correctly

src/checkers/inference/solver/backend/z3/encoder/Z3BitVectorConstraintEncoderFactory.java
Should increase visiability of `context` and `z3BVFormatTranslator` field from `private` to `protected`, so that subclasses of `Z3ConstraintEncoderFactory ` can use these two fields.
=> Increase visiability of context and z3BVFormatTranslator field in Z3ConstraintEncoderFactory

src/checkers/inference/VariableAnnotator.java
Now we should keep only `@VarAnno` on a type when doing inference. Therefore `variableAnnotator` should not add `@RealTop` to a type anymore.
=> Do not add real top qual when adding primary varAnnot for a given type.

src/checkers/inference/util/JaifBuilder.java
This PR rewrites `buildAnnotationHeader()` in `JaifBuilder` to fully support all annotation method return types (ie, primitives, String, Class, Enum, Annotation, and 1D arrays with a component type of one of these 5 types).
To support Annotations used as method return types within an annotation, the JaifBuilder will also output annotation headers for the return type annotation ***_before_*** the annotation that uses it as a return type. This is done recursively as well for the return type annotation.
===
All of the return types can be exercised by inserting the `Annot` annotation, defined in a file as:
```
@interface InnerRTAnnot {}
@interface ReturnTypeAnnot {
InnerRTAnnot annot() default @InnerRTAnnot;
InnerRTAnnot[] annots() default {};
}
enum SomeEnum {
ENUMVAL;
}
public @interface …
```
=> Enable JaifBuilder to fully support all annotation method return types

src/checkers/inference/InferenceAnnotatedTypeFactory.java
As the raw`VarAnnot` never make sense to be a default qualifier, therefore the `InferenceQualDefault` should be initialized with `realATF`, instead of `inferATF`.
=> In InferATF, passing realATF when initializing InferenceQualDefault.

src/checkers/inference/model/ConstantSlot.java
it never make sense to create a `ConstantSlot` with a `VarAnnot` as its value (the `realQual` constant).
Add checks on the `value` when constructing a `ConstantSlot`, error abort if the `value` is a `VarAnnot`.
=> Add check on value when creating ConstantSlot.

src/checkers/inference/solver/backend/encoder/ConstraintEncoderCoordinator.java
quick cleanup PR:
- get rid of `SlotSlotCombo combo` variable and move the expression directly into the switch statement
- formats the constraint encoder coordinator file for 80 char / line
=> remove combo variable and format constraint encoder coordinator

src/checkers/inference/DefaultSlotManager.java
since the if statement in `DefaultSlotManager.getAnnotation()` checks to see if slot class is a variable slot or any of its subclasses, and recent PRs have to add new cases to this statement for new subclasses, lets just change it to a proper check.
also formatted the code in the method.
=> update slot class check in DefaultSlotManager.getAnnotation

src/checkers/inference/InferenceLauncher.java
Changes:
- Using `List` to construct `options`, instead of using `Array` with hardcoding indices
- Concatenate argument and its value into one element, (e.g. `add("--outdir=" + outputDir.getAbsolutePath())`), instead of using two consecutive elements which adding implicit constraints on orders of these two elements
- Enable printing out the error stack when exceptions thrown from AFU, which is helpful for debugging.
=> Using List to construct options, instead of using Array with hardcoding indices for launching insert-annotation-to-source

src/checkers/inference/solver/backend/z3/Z3BitVectorFormatTranslator.java
This PR made below changes:
- Add `postInitWithContext()` method: this method is for sub-classes to initialize objects that needs `context`. (which is laze-initialized by `initContext()` method, and not initialized yet during constructor phase).
- Improve `solver` visibility from `private` to `protected`: some cases do need add additional constraints to `solver`, (e.g. add assertion constraint "that each variable slot should not equal to bottom). Therefore I improved the visibility of `solver` to provide more flexibility for sub-classes.
Note: the side effect is this do allow sub-classes add arbitrary constraints into the solver. Maybe a
better solution would be we generated complete constraints during constraint generation phase.
However, for the example case, I currently choose to add …
=> Add postContextInit() method. Add defensive check on serializeVarSlot() method.

src/checkers/inference/BaseInferrableChecker.java, src/checkers/inference/InferenceMain.java, src/checkers/inference/InferrableChecker.java
This PR enables the insertion of alias annotations into source code, by providing a mechanism for a type checker to specify a set of additional annotation classes that are inserted as annotation headers into the JAIF file. The missing annotation headers are preventing the insertion of alias annotations by AFU.
The default implementation returns and empty set. In Units inference, a set of alias annotation classes are returned.
=> Enable insertion of additional annotation headers to JAIF

src/checkers/inference/InferenceLauncher.java
For example, to enable use of -AprintErrorStack:
`--cfArgs="-AprintErrorStack"`
which helps to debug errors
Sample output with -AprintErrorStack
```
/home/jeff/jsr308/units-inference/bin
--- Typechecking ---
error: SourceChecker.typeProcessingStart: unexpected Throwable (RuntimeException); message: Could not load class 'units.qual.UnitsInternal' for field 'value' in annotation @org.checkerframework.framework.qual.PolymorphicQualifier(units.qual.UnitsInternal.class)
Exception: java.lang.RuntimeException: Could not load class 'units.qual.UnitsInternal' for field 'value' in annotation @org.checkerframework.framework.qual.PolymorphicQualifier(units.qual.UnitsInternal.class); Stack trace: org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:51) …
```
=> Allow passing of cfArgs to typecheck mode

build.gradle, tests/checkers/inference/DataflowInferenceTest.java, tests/checkers/typecheck/DataflowTypecheckTest.java
each test is now individually invokeable by its name, and the list is shown on `gradle tasks` :
```
Verification tasks
------------------
check - Runs all checks.
DataflowInferenceTest - Run DataflowInferenceTest tests.
DataflowTypecheckTest - Run DataflowTypecheckTest tests.
DefaultSlotManagerTest - Run DefaultSlotManagerTest tests.
IFlowSinkPropTest - Run IFlowSinkPropTest tests.
IFlowSinkSatTest - Run IFlowSinkSatTest tests.
IFlowSourcePropTest - Run IFlowSourcePropTest tests.
IFlowSourceSatTest - Run IFlowSourceSatTest tests.
InterningTest - Run InterningTest tests.
OsTrustedTest - Run OsTrustedTest tests.
OstrustedTest - Run OstrustedTest tests.
test - Runs the unit tests.
```
also renamed the two Dataflow tests so they have unique names for the gradle menu
=> update gradle script to be able to run each test individually by its name

src/checkers/inference/solver/SolverEngine.java, src/checkers/inference/solver/backend/lingeling/LingelingSolver.java, src/checkers/inference/solver/backend/logiql/LogiQLPredicateGenerator.java, src/checkers/inference/solver/backend/logiql/LogiQLSolver.java, src/checkers/inference/solver/backend/maxsat/MaxSatSolver.java, src/checkers/inference/solver/strategy/GraphSolvingStrategy.java, src/checkers/inference/solver/util/PrintUtils.java, src/checkers/inference/solver/util/StatisticRecorder.java, src/checkers/inference/solver/util/Statistics.java, src/dataflow/solvers/general/DataflowGraphSolvingStrategy.java, tests/checkers/system/StatisticsMultithreadTest.java
Change statistics collection mechanism:
- Statistics are now keyed on strings, and are stored in a LinkedHashMap.
- All collected statistics are printed.
- Migrated code which collected statistics on number of slots and constraints from `SolverEngine` to `StatisticRecorder`, and generalized it to collect stats based on the run-time class of each slot and constraint.
- Renamed `StatisticRecorder` to `Statistics`
- Added JUnit test for `Statistics` to test its static methods in a multithreaded environment.
Sample stats output for ontology:
```
====================== Statistics =======================
total_slots: 27
total_variable_slots: 20
constantslot: 7
variableslot: 18
existentialvariableslot: 2
total_constraints: 15
subtypeconstraint: 14
existentialconstraint: 1 …
```
=> Upgrade statistics mechanism

.travis-build.sh, README.md, build.gradle
This PR fixes #207. It adds a new Gradle target `cloneAndBuildDependencies`, adapts the Travis build script to call it, and updates the README file accordingly.
=> Add clone and build deps target

scripts/buildLingeling, src/checkers/inference/solver/backend/lingeling/LingelingSolver.java, testing/dataflowexample/travis-test.sh
Hello, in this PR, I copy the executable file Lingeling to CIF/lib and change the corresponding code to support this change. I did not think out a better way to get the path of CIF, so I still use the `getProperty("user.dir")` function to achieve this. If you have any advice, please let me know.
=> Copy Lingeling to CIF/lib, resolve #215.

scripts/buildZ3
Hello, this PR fixes a simple error. 
When buildZ3 is called, there will be an error which is because that `[[ ]]` is only supported in bash. Since we do not specify  `/bin/bash` but using `/bin/sh`, this error occurs. 
The error info is in [here](https://travis-ci.org/opprop/checker-framework/jobs/532566064#L1418).
=> Fix buildZ3 double brackets not found

src/checkers/inference/DefaultSlotManager.java, src/checkers/inference/solver/frontend/LatticeBuilder.java
Since `getTypeQualifiers()` is finally removed in typetools/CF, the usages are all replaced with real type factory's `getSupportedTypeQualifiers()`
=> Remove usages of getTypeQualifiers()

README.md
The `MaxSat` backend solver is mistakenly written as `MaxSAT`, which causes crash while creating the solver factory reflectively.
=> Correct solver name from `MaxSAT` to `MaxSat`

.github/workflows/main.yml
So the CI runs through, instead of terminating at the first failure.
=> Disable fail-fast

src/checkers/inference/DefaultSlotManager.java, src/checkers/inference/InferenceVisitor.java, src/checkers/inference/SlotManager.java, src/checkers/inference/dataflow/InferenceTransfer.java
Remove the hack at https://github.com/opprop/checker-framework-inference/blob/939619aacfe930e0ff9f5dfc637f3556b0842f88/src/checkers/inference/dataflow/InferenceTransfer.java#L233
Each time when a new refinement variable is created, an equality constraint is created with it. Since in SSA form, an intermediate variable is assigned once and never changes.
Right now flow refinement is adapted for non-type-variable only.
=> Adapt flow refinement in inference

src/checkers/inference/InferenceAnnotatedTypeFactory.java, src/checkers/inference/InferenceQualifierHierarchy.java, src/checkers/inference/VariableAnnotator.java
1. returns expected `@VarAnnot(?)` for `InferenceAnnotatedTypeFactory.getTypeDeclarationBounds`.
2. type declaration bound should be a normal source variable slot, instead of existential slot.
3. incorporate part of https://github.com/opprop/checker-framework-inference/pull/294, such that not to create existential slots for class bounds, i.e. type declaration bounds are always explicit in inference.
=> Type declaration bounds in inference

src/checkers/inference/VariableAnnotator.java
`getOrCreateDeclBound()` can now be overridden and developers of a type system (e.g., universe type system) can exclude class declaration annotations.
=> changed access modifier of getOrCreateDeclBound() to protected

src/checkers/inference/VariableAnnotator.java, testdata/ostrusted-inferrable-test/ConstantArray.java, testdata/ostrusted-inferrable-test/Constants.java
Found a case that causes crash,
```
public interface Constants {
String[] ACCESS_NAMES = {
"public", "private", "protected", "static", "final", "synchronized",
"volatile", "transient", "native", "interface", "abstract", "strictfp",
"synthetic", "annotation", "enum"
};
}
```
The reason is that in `VariableAnnotator.annotateArrayLiteral`, it firstly check if the array is an annotation element, by calling `enclosedByAnnotation`, which triggers NullPointerException when the array is declared in an interface.
=> Fix crash when an interface contains an array literal

src/checkers/inference/DefaultSlotManager.java, src/checkers/inference/SlotManager.java, src/checkers/inference/model/ArithmeticVariableSlot.java
Record the TypeKind of the arithmetic operation result, which indicates the value range.
The result depends on the wider operand. i.e.
- If both sides are int or narrower than int => arithmetic slot's type kind int
- If one side is long => arithmetic slot's type kind is long
=> Record the TypeKind of arithmetic operation in ArithmeticVariableSlot

src/checkers/inference/DefaultSlotManager.java, src/checkers/inference/InferenceAnnotatedTypeFactory.java, src/checkers/inference/InferenceChecker.java, src/checkers/inference/InferenceMain.java, src/checkers/inference/InferenceVisitor.java, src/checkers/inference/SlotManager.java, src/checkers/inference/util/SlotDefaultTypeResolver.java
Currently, all checkers in inference may crash on the following code:
```
public class VectorTest {
}
class Vector {
int x;
int y;
int z;
public static Vector max(Vector a, Vector b) {
int aLength = a.length();
int bLength = b.length();
// test lub of polys
if (aLength > bLength) {
return a;
}
return b;
}
public int length() {
return x * x + y * y + z * z;
}
}
```
This is because `AbstractTypeProcessor::typeProcess` only receives one fully-analyzed top-level class at a time, while `SlotDefaultTypeResolver` tries to compute the default types for the entire compilation unit. Details about the crash:
1. The inference checker (which implements `AbstractTypeProcessor`) receives a call to type process the top-level class `VectorTest`.
2. Although the top-level class `Vector` is also under the …
=> Avoid reading type info from trees that are not being processed

settings.gradle, src/checkers/inference/DefaultSlotManager.java, src/checkers/inference/InferenceAnnotatedTypeFactory.java, src/checkers/inference/InferenceQualifierPolymorphism.java, src/checkers/inference/SlotManager.java, src/checkers/inference/VariableAnnotator.java
1. Check `isPolymorphicQualifier` with the real type factory for constant slot.
2. Add `createPolymorphicInstanceSlot` to slot manager since it's not really a source variable. Currently, we are using source variable slot for polymorphic instance because it doesn't affect the inference result.
3. A minor change for CFI setup: `settings.gradle` wasn't working properly under some environments.
Note: This PR is related to https://github.com/opprop/ontology/pull/58 since it introduces the polymorphic annotation `@Ontology(values={POLY})`
=> Fix polymorphism check and introduce the concept of `PolymorphicInstanceSlot`

.github/workflows/main.yml, gradle/wrapper/gradle-wrapper.properties
To fix all downstream Java 17 tests, we need the following changes:
1. Use maven 3.8.6 which supports JDK 17
2. Create a fork of https://github.com/hwinkler/matrix-toolkits-java at https://github.com/opprop-benchmarks/hwinkler-matrix-toolkits-java so that we can update its compile source and target to 1.8.
3. Update other projects (in https://github.com/opprop-benchmark) that are used by downstream projects. We need to make sure their compile source and target are >= 1.7.
4. Update security-demo: https://github.com/opprop/security-demo/pull/19
5. Update ontology: https://github.com/opprop/ontology/pull/78
=> Update maven and gradle

build.gradle
Based on the CHANGELOG, 
Version 3.4.0 (May 3, 2020)
---------------------------
The annotated jdk8.jar is no longer used.  You should remove any occurrence of
-Xbootclasspath/p:.../jdk8.jar
from your build scripts.  Annotations for JDK 8 are included in checker.jar.
I have removed the jdk8.jar in the task dist.
=> Remove use of no-longer-existing jdk8.jar file

.ci-build-without-test.sh
We should use eisop-plume-lib and update the script after pull changes from plume-lib to it, otherwise no CI will work now.
=> Use eisop plume lib first
